INSERT INTO return_limit
VALUES (100);

INSERT INTO drug
VALUES (1, 'Heroin',
        'Heroin is a highly addictive opioid drug derived from morphine, which is obtained from the opium poppy. It is typically sold as a white or brownish powder.'),
       (2, 'Cocaine',
        'Cocaine is a powerful stimulant drug derived from the coca plant. It is commonly snorted, smoked, or injected for its euphoric effects.'),
       (3, 'LSD',
        'LSD, also known as acid, is a hallucinogenic drug that alters perception, mood, and cognitive processes. It is typically consumed orally.'),
       (4, 'MDMA',
        'MDMA, commonly known as ecstasy or molly, is a synthetic drug with stimulant and hallucinogenic properties. It is often used recreationally for its euphoric effects.'),
       (5, 'Methamphetamine',
        'Methamphetamine is a potent central nervous system stimulant that is commonly abused for its stimulating and euphoric effects. It can be smoked, snorted, injected, or swallowed.'),
       (6, 'Crack Cocaine',
        'Crack cocaine is a highly potent and addictive form of cocaine that is smoked. It produces a rapid and intense high, but its effects are short-lived.'),
       (7, 'PCP',
        'PCP, or phencyclidine, is a dissociative drug that can cause hallucinations, delusions, and extreme agitation. It is commonly smoked, snorted, or ingested orally.'),
       (8, 'Morphine',
        'Morphine is a potent opioid pain medication that is used to treat severe pain. It is derived from the opium poppy and can be taken orally, injected, or used in suppository form.'),
       (9, 'Opium',
        'Opium is a highly addictive narcotic drug derived from the opium poppy. It contains several opioid alkaloids, including morphine and codeine, and is typically smoked, eaten, or brewed into tea.'),
       (10, 'Ketamine',
        'Ketamine is a dissociative anesthetic that is used medically for anesthesia and pain relief. It is also abused recreationally for its hallucinogenic effects.'),
       (11, 'Psilocybin',
        'Psilocybin is a naturally occurring psychedelic compound found in certain species of mushrooms. It produces hallucinogenic effects and is commonly consumed for its psychoactive properties.'),
       (12, 'GHB',
        'GHB, or gamma-hydroxybutyrate, is a central nervous system depressant that is used medically for anesthesia and narcolepsy treatment. It is also abused recreationally for its euphoric effects.'),
       (13, 'Fentanyl',
        'Fentanyl is a powerful synthetic opioid analgesic that is similar to morphine but is 50 to 100 times more potent. It is commonly used medically for pain management and anesthesia.'),
       (14, 'Krokodil',
        'Krokodil is a homemade opioid drug that is synthesized from codeine and other toxic chemicals. It is highly addictive and causes severe tissue damage and necrosis at injection sites.'),
       (15, 'Bath Salts',
        'Bath salts are a group of synthetic cathinones that are chemically similar to amphetamines. They are often sold as legal alternatives to illicit drugs and can cause severe hallucinations and agitation.'),
       (16, 'Mescaline',
        'Mescaline is a naturally occurring psychedelic alkaloid found in various cactus species, most notably peyote. It produces hallucinogenic effects and is commonly used in religious and spiritual ceremonies.'),
       (17, 'DMT',
        'DMT, or N,N-Dimethyltryptamine, is a powerful hallucinogenic compound found in certain plants and animals. It produces intense, short-lived psychedelic experiences when smoked, snorted, or injected.'),
       (18, 'Flakka',
        'Flakka, also known as alpha-PVP, is a synthetic cathinone stimulant that is similar to bath salts. It can cause extreme agitation, paranoia, and hallucinations when abused.'),
       (19, 'Khat',
        'Khat is a flowering plant native to East Africa and the Arabian Peninsula. Its leaves contain psychoactive compounds, including cathinone and cathine, and are chewed for their stimulant effects.'),
       (20, 'Salvia',
        'Salvia divinorum is a psychoactive plant that contains salvinorin A, a potent hallucinogen. It is commonly smoked or chewed for its short-lived but intense psychedelic effects.'),
       (21, 'Spice',
        'Spice is a mixture of herbs and synthetic cannabinoids that produce effects similar to marijuana when smoked. It is often marketed as a legal alternative to cannabis but can cause severe adverse reactions.'),
       (22, 'Ecstasy',
        'Ecstasy, also known as MDMA or molly, is a synthetic drug with stimulant and hallucinogenic properties. It is commonly used recreationally for its euphoric effects, increased energy, and enhanced sensory perception.'),
       (23, 'Mushrooms',
        'Magic mushrooms, or psilocybin mushrooms, are fungi that contain psilocybin and psilocin, psychedelic compounds that produce hallucinogenic effects. They are commonly consumed for their psychoactive properties.'),
       (24, 'Peyote',
        'Peyote is a small, spineless cactus that contains mescaline, a powerful hallucinogen. It has been used for centuries by indigenous peoples in religious ceremonies and for healing purposes.'),
       (25, 'Ayahuasca',
        'Ayahuasca is a psychoactive brew that contains the psychedelic compound DMT and a monoamine oxidase inhibitor (MAOI). It is used in traditional Amazonian shamanic ceremonies for healing and spiritual exploration.'),
       (26, 'Dextroamphetamine',
        'Dextroamphetamine is a central nervous system stimulant that is used to treat attention deficit hyperactivity disorder (ADHD) and narcolepsy. It increases alertness, concentration, and energy levels.'),
       (27, 'Oxycodone',
        'Oxycodone is a powerful opioid pain medication that is used to treat moderate to severe pain. It is commonly prescribed in various forms, including immediate-release tablets and extended-release capsules.'),
       (28, 'Rohypnol',
        'Rohypnol, also known as flunitrazepam, is a benzodiazepine sedative-hypnotic drug that is used medically for anesthesia and insomnia treatment. It is also infamously known as a "date rape drug" due to its association with drug-facilitated sexual assault.'),
       (29, 'Xanax',
        'Xanax, also known as alprazolam, is a benzodiazepine medication that is used to treat anxiety and panic disorders. It produces calming effects by enhancing the effects of a neurotransmitter called gamma-aminobutyric acid (GABA).'),
       (30, 'Codeine',
        'Codeine is an opioid medication that is used to treat mild to moderate pain and to suppress coughing. It is commonly found in combination with other medications, such as acetaminophen or ibuprofen, in prescription and over-the-counter products.'),
       (31, 'Vicodin',
        'Vicodin is a combination medication that contains hydrocodone, an opioid pain reliever, and acetaminophen, a non-opioid pain reliever and fever reducer. It is used to treat moderate to severe pain.'),
       (32, 'Adderall',
        'Adderall is a combination medication that contains amphetamine and dextroamphetamine, central nervous system stimulants. It is used to treat attention deficit hyperactivity disorder (ADHD) and narcolepsy by increasing focus, attention, and energy levels.'),
       (33, 'Valium',
        'Valium, also known as diazepam, is a benzodiazepine medication that is used to treat anxiety, muscle spasms, seizures, and alcohol withdrawal symptoms. It produces calming effects by enhancing the effects of a neurotransmitter called gamma-aminobutyric acid (GABA).'),
       (34, 'Ritalin',
        'Ritalin, also known as methylphenidate, is a central nervous system stimulant medication that is used to treat attention deficit hyperactivity disorder (ADHD) and narcolepsy. It increases alertness, concentration, and energy levels.'),
       (37, 'OxyContin',
        'OxyContin is an extended-release formulation of oxycodone, a potent opioid pain medication. It is used to treat moderate to severe pain that requires around-the-clock pain relief.'),
       (38, 'Ambien',
        'Ambien, also known as zolpidem, is a sedative-hypnotic medication that is used to treat insomnia. It works by slowing down brain activity to help patients fall asleep faster and stay asleep longer.'),
       (39, 'Lunesta',
        'Lunesta, also known as eszopiclone, is a sedative-hypnotic medication that is used to treat insomnia. It works by enhancing the activity of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity, to promote sleep.'),
       (40, 'Ativan',
        'Ativan, also known as lorazepam, is a benzodiazepine medication that is used to treat anxiety disorders, insomnia, and alcohol withdrawal symptoms. It produces calming effects by enhancing the effects of a neurotransmitter called gamma-aminobutyric acid (GABA).'),
       (41, 'Tramadol',
        'Tramadol is a synthetic opioid pain medication that is used to treat moderate to moderately severe pain. It works by binding to opioid receptors in the brain and spinal cord to inhibit the transmission of pain signals.'),
       (42, 'Demerol',
        'Demerol, also known as meperidine, is a synthetic opioid pain medication that is used to treat moderate to severe pain. It works by binding to opioid receptors in the brain and spinal cord to inhibit the transmission of pain signals.'),
       (43, 'Suboxone',
        'Suboxone is a combination medication that contains buprenorphine, a partial opioid agonist, and naloxone, an opioid antagonist. It is used to treat opioid dependence and addiction by reducing cravings and withdrawal symptoms.'),
       (44, 'Methadone',
        'Methadone is a synthetic opioid medication that is used to treat opioid dependence and addiction. It works by binding to opioid receptors in the brain and blocking the effects of other opioids, reducing cravings and withdrawal symptoms.'),
       (45, 'Dilaudid',
        'Dilaudid, also known as hydromorphone, is a potent opioid pain medication that is used to treat moderate to severe pain. It works by binding to opioid receptors in the brain and spinal cord to inhibit the transmission of pain signals.'),
       (46, 'Norco',
        'Norco is a combination medication that contains hydrocodone, an opioid pain reliever, and acetaminophen, a non-opioid pain reliever and fever reducer. It is used to treat moderate to severe pain.'),
       (47, 'Hydrocodone',
        'Hydrocodone is an opioid pain medication that is used to treat moderate to severe pain. It is commonly found in combination with other medications, such as acetaminophen or ibuprofen, in prescription and over-the-counter products.'),
       (48, 'Vyvanse',
        'Vyvanse, also known as lisdexamfetamine, is a central nervous system stimulant medication that is used to treat attention deficit hyperactivity disorder (ADHD) and binge eating disorder. It works by increasing the levels of dopamine and norepinephrine in the brain.'),
       (49, 'Clonazepam',
        'Clonazepam is a benzodiazepine medication that is used to treat panic disorder, seizures, and certain types of movement disorders. It produces calming effects by enhancing the effects of a neurotransmitter called gamma-aminobutyric acid (GABA).'),
       (50, 'Soma',
        'Soma, also known as carisoprodol, is a muscle relaxant medication that is used to treat musculoskeletal pain and discomfort. It works by blocking pain sensations between the nerves and the brain.'),
       (51, 'Gabapentin',
        'Gabapentin is an anticonvulsant medication that is used to treat seizures, nerve pain, and certain types of mood disorders. It works by affecting the neurotransmitters involved in nerve signaling and pain sensation.'),
       (52, 'Zolpidem',
        'Zolpidem is a sedative-hypnotic medication that is used to treat insomnia. It works by slowing down brain activity to help patients fall asleep faster and stay asleep longer.'),
       (53, 'Morphine Sulfate',
        'Morphine sulfate is a potent opioid pain medication that is used to treat severe pain. It is derived from the opium poppy and can be taken orally, injected, or used in suppository form.'),
       (54, 'Percocet',
        'Percocet is a combination medication that contains oxycodone, an opioid pain reliever, and acetaminophen, a non-opioid pain reliever and fever reducer. It is used to treat moderate to severe pain.'),
       (55, 'Lortab',
        'Lortab is a combination medication that contains hydrocodone, an opioid pain reliever, and acetaminophen, a non-opioid pain reliever and fever reducer. It is used to treat moderate to moderately severe pain.'),
       (56, 'Concerta',
        'Concerta is a central nervous system stimulant medication that is used to treat attention deficit hyperactivity disorder (ADHD) in children and adults. It works by increasing the levels of dopamine and norepinephrine in the brain.'),
       (57, 'Fioricet',
        'Fioricet is a combination medication that contains acetaminophen, butalbital, and caffeine. It is used to treat tension headaches and migraines by relaxing muscle contractions and constricting blood vessels in the brain.'),
       (58, 'Buprenorphine',
        'Buprenorphine is a partial opioid agonist medication that is used to treat opioid dependence and addiction. It works by binding to opioid receptors in the brain and blocking the effects of other opioids, reducing cravings and withdrawal symptoms.'),
       (59, 'Butalbital',
        'Butalbital is a barbiturate medication that is used to treat tension headaches and migraines. It works by relaxing muscle contractions and constricting blood vessels in the brain.'),
       (60, 'Cymbalta',
        'Cymbalta, also known as duloxetine, is a serotonin-norepinephrine reuptake inhibitor (SNRI) medication that is used to treat depression, anxiety, and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (61, 'Promethazine',
        'Promethazine is a phenothiazine antihistamine medication that is used to treat allergic reactions, nausea, vomiting, and motion sickness. It works by blocking the action of histamine and other neurotransmitters involved in nausea and vomiting.'),
       (62, 'Wellbutrin',
        'Wellbutrin, also known as bupropion, is an atypical antidepressant medication that is used to treat depression and seasonal affective disorder (SAD). It works by increasing the levels of dopamine and norepinephrine in the brain.'),
       (63, 'Prozac',
        'Prozac, also known as fluoxetine, is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat depression, anxiety, obsessive-compulsive disorder (OCD), and certain eating disorders. It works by increasing the levels of serotonin in the brain.'),
       (64, 'Zoloft',
        'Zoloft, also known as sertraline, is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat depression, obsessive-compulsive disorder (OCD), panic disorder, and certain anxiety disorders. It works by increasing the levels of serotonin in the brain.'),
       (65, 'Paxil',
        'Paxil, also known as paroxetine, is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat depression, obsessive-compulsive disorder (OCD), panic disorder, and certain anxiety disorders. It works by increasing the levels of serotonin in the brain.'),
       (66, 'Lexapro',
        'Lexapro, also known as escitalopram, is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat depression and certain anxiety disorders. It works by increasing the levels of serotonin in the brain.'),
       (67, 'Celexa',
        'Celexa, also known as citalopram, is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat depression and certain anxiety disorders. It works by increasing the levels of serotonin in the brain.'),
       (68, 'Effexor',
        'Effexor, also known as venlafaxine, is a serotonin-norepinephrine reuptake inhibitor (SNRI) medication that is used to treat depression, anxiety, and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (69, 'Citalopram',
        'Citalopram is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat depression and certain anxiety disorders. It works by increasing the levels of serotonin in the brain.'),
       (70, 'Tricyclic Antidepressants',
        'Tricyclic antidepressants are a class of medications that are used to treat depression, anxiety, and certain other mood disorders. They work by increasing the levels of serotonin and norepinephrine in the brain.'),
       (71, 'Trazodone',
        'Trazodone is a serotonin antagonist and reuptake inhibitor (SARI) medication that is used to treat depression and insomnia. It works by increasing serotonin levels and blocking certain serotonin receptors in the brain.'),
       (72, 'Amitriptyline',
        'Amitriptyline is a tricyclic antidepressant medication that is used to treat depression, neuropathic pain, and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (73, 'Doxepin',
        'Doxepin is a tricyclic antidepressant medication that is used to treat depression, anxiety, and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (74, 'Nortriptyline',
        'Nortriptyline is a tricyclic antidepressant medication that is used to treat depression, neuropathic pain, and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (75, 'Desipramine',
        'Desipramine is a tricyclic antidepressant medication that is used to treat depression and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (76, 'Imipramine',
        'Imipramine is a tricyclic antidepressant medication that is used to treat depression, enuresis (bedwetting), and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (77, 'Amoxapine',
        'Amoxapine is a tricyclic antidepressant medication that is used to treat depression. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (78, 'Maprotiline',
        'Maprotiline is a tetracyclic antidepressant medication that is used to treat depression. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (79, 'Trimipramine',
        'Trimipramine is a tricyclic antidepressant medication that is used to treat depression and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (80, 'Fluoxetine',
        'Fluoxetine, also known as Prozac, is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat depression, obsessive-compulsive disorder (OCD), panic disorder, and certain eating disorders. It works by increasing the levels of serotonin in the brain.'),
       (81, 'Sertraline',
        'Sertraline, also known as Zoloft, is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat depression, obsessive-compulsive disorder (OCD), panic disorder, and certain anxiety disorders. It works by increasing the levels of serotonin in the brain.'),
       (82, 'Paroxetine',
        'Paroxetine, also known as Paxil, is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat depression, obsessive-compulsive disorder (OCD), panic disorder, and certain anxiety disorders. It works by increasing the levels of serotonin in the brain.'),
       (83, 'Fluvoxamine',
        'Fluvoxamine is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat obsessive-compulsive disorder (OCD) and certain anxiety disorders. It works by increasing the levels of serotonin in the brain.'),
       (84, 'Escitalopram',
        'Escitalopram, also known as Lexapro, is a selective serotonin reuptake inhibitor (SSRI) medication that is used to treat depression and certain anxiety disorders. It works by increasing the levels of serotonin in the brain.'),
       (85, 'Venlafaxine',
        'Venlafaxine, also known as Effexor, is a serotonin-norepinephrine reuptake inhibitor (SNRI) medication that is used to treat depression, anxiety, and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (86, 'Duloxetine',
        'Duloxetine, also known as Cymbalta, is a serotonin-norepinephrine reuptake inhibitor (SNRI) medication that is used to treat depression, anxiety, and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (87, 'Milnacipran',
        'Milnacipran is a serotonin-norepinephrine reuptake inhibitor (SNRI) medication that is used to treat fibromyalgia and certain types of chronic pain. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (88, 'Levomilnacipran',
        'Levomilnacipran is a serotonin-norepinephrine reuptake inhibitor (SNRI) medication that is used to treat major depressive disorder. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (89, 'Desvenlafaxine',
        'Desvenlafaxine, also known as Pristiq, is a serotonin-norepinephrine reuptake inhibitor (SNRI) medication that is used to treat major depressive disorder. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (90, 'Nefazodone',
        'Nefazodone is a serotonin antagonist and reuptake inhibitor (SARI) medication that is used to treat depression. It works by increasing serotonin levels and blocking certain serotonin receptors in the brain.'),
       (92, 'Vilazodone',
        'Vilazodone is a serotonin antagonist and reuptake inhibitor (SARI) medication that is used to treat depression. It works by increasing serotonin levels and blocking certain serotonin receptors in the brain.'),
       (93, 'Mirtazapine',
        'Mirtazapine is a noradrenergic and specific serotonergic antidepressant (NaSSA) medication that is used to treat depression. It works by increasing the levels of serotonin and norepinephrine in the brain.'),
       (94, 'Bupropion',
        'Bupropion, also known as Wellbutrin or Zyban, is an atypical antidepressant medication that is used to treat depression, seasonal affective disorder (SAD), and to aid in smoking cessation. It works by increasing the levels of dopamine and norepinephrine in the brain.'),
       (101, 'Sativa', 'Energetic, uplifting, cerebral high with creative effects.'),
       (102, 'Indica', 'Relaxing, sedating, body high with pain relief effects.'),
       (103, 'Hybrid', 'Combines Sativa and Indica effects for balanced experience.'),
       (104, 'Ruderalis', 'Low THC, autoflowering cannabis used in breeding.'),
       (105, 'OG Kush', 'Potent Indica with earthy, pine, and citrus flavors.'),
       (106, 'White Widow', 'Balanced hybrid with euphoric and creative effects.'),
       (107, 'Northern Lights', 'Indica with relaxing, euphoric, and sleepy effects.'),
       (108, 'Blue Dream', 'Hybrid with uplifting, euphoric, and relaxing effects.'),
       (109, 'Girl Scout Cookies', 'Hybrid with euphoric, relaxing, and creative effects.'),
       (110, 'AK-47', 'Sativa-dominant hybrid with relaxed, happy, and uplifting effects.'),
       (111, 'Purple Haze', 'Sativa-dominant hybrid with psychedelic and euphoric effects.'),
       (112, 'Trainwreck', 'Potent Sativa-dominant hybrid with energetic and euphoric effects.'),
       (113, 'Jack Herer', 'Sativa-dominant hybrid with blissful, clear-headed, and creative effects.'),
       (114, 'Pineapple Express', 'Sativa-dominant hybrid with energetic and uplifting effects.'),
       (115, 'Durban Poison', 'Pure Sativa with uplifting, energetic, and cerebral effects.'),
       (116, 'Super Silver Haze', 'Sativa-dominant hybrid with euphoric and uplifting effects.'),
       (117, 'Gorilla Glue', 'Potent hybrid with couch-locking and euphoric effects.'),
       (118, 'Bruce Banner', 'Hybrid with euphoric, energizing, and creative effects.'),
       (119, 'Chemdawg', 'Hybrid with cerebral, euphoric, and creative effects.'),
       (120, 'Granddaddy Purple', 'Indica with relaxing, euphoric, and sleepy effects.'),
       (121, 'Amnesia Haze', 'Sativa-dominant hybrid with uplifting and euphoric effects.'),
       (122, 'Skywalker OG', 'Indica-dominant hybrid with relaxing and sedating effects.'),
       (123, 'Gelato', 'Hybrid with relaxing, euphoric, and uplifting effects.'),
       (124, 'Green Crack', 'Sativa with energizing, uplifting, and focused effects.'),
       (125, 'Critical Mass', 'Indica with relaxing, sleepy, and euphoric effects.'),
       (126, 'Maui Wowie', 'Sativa with euphoric, energetic, and creative effects.'),
       (127, 'Tangie', 'Sativa-dominant hybrid with citrusy, uplifting, and euphoric effects.'),
       (128, 'Cherry Pie', 'Indica-dominant hybrid with euphoric and relaxing effects.'),
       (129, 'Cookies and Cream', 'Hybrid with relaxing, happy, and euphoric effects.'),
       (130, 'Chocolope', 'Sativa with uplifting, euphoric, and energizing effects.'),
       (131, 'Blue Cheese', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (132, 'Lemon Haze', 'Sativa-dominant hybrid with uplifting and energetic effects.'),
       (133, 'Purple Kush', 'Indica with relaxing, euphoric, and sleepy effects.'),
       (134, 'Sour Diesel', 'Sativa with energizing, uplifting, and euphoric effects.'),
       (135, 'Platinum OG', 'Indica with relaxing, sedating, and euphoric effects.'),
       (136, 'GSC (f.k.a. Girl Scout Cookies)', 'Hybrid with euphoric, relaxing, and creative effects.'),
       (137, 'Death Star', 'Indica-dominant hybrid with sedating and euphoric effects.'),
       (138, 'Blackberry Kush', 'Indica-dominant hybrid with relaxing and sleepy effects.'),
       (139, 'Bubba Kush', 'Indica with relaxing, sleepy, and euphoric effects.'),
       (140, 'Harlequin', 'High-CBD hybrid with relaxed, focused, and alert effects.'),
       (141, 'Super Lemon Haze', 'Sativa-dominant hybrid with uplifting and energetic effects.'),
       (142, 'Agent Orange', 'Sativa-dominant hybrid with euphoric and creative effects.'),
       (143, 'Chemdawg 91', 'Hybrid with cerebral, euphoric, and relaxing effects.'),
       (144, 'Headband', 'Hybrid with relaxing, euphoric, and focused effects.'),
       (145, 'Black Widow', 'Sativa-dominant hybrid with euphoric and relaxing effects.'),
       (146, 'Grape Ape', 'Indica with relaxing, sleepy, and euphoric effects.'),
       (147, 'Cannatonic', 'High-CBD hybrid with relaxed, happy, and focused effects.'),
       (148, 'Super Skunk', 'Indica with relaxed, happy, and euphoric effects.'),
       (149, 'Blueberry', 'Indica-dominant hybrid with relaxed, sleepy, and euphoric effects.'),
       (150, 'Strawberry Cough', 'Sativa with uplifting, euphoric, and energetic effects.'),
       (151, 'Kandy Kush', 'Indica-dominant hybrid with euphoric and relaxed effects.'),
       (152, 'Blueberry Kush', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (153, 'Tahoe OG Kush', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (154, 'Gorilla Cookies', 'Hybrid with euphoric, relaxed, and focused effects.'),
       (155, 'Purple Urkle', 'Indica with relaxing, sleepy, and euphoric effects.'),
       (156, 'AK-48', 'Sativa-dominant hybrid with relaxed, euphoric, and happy effects.'),
       (157, 'Cinderella 99', 'Sativa-dominant hybrid with euphoric and energetic effects.'),
       (158, 'Golden Goat', 'Sativa-dominant hybrid with happy, uplifted, and euphoric effects.'),
       (159, 'Bubblegum Kush', 'Indica-dominant hybrid with euphoric and relaxing effects.'),
       (160, 'Alien OG', 'Indica with relaxing, euphoric, and happy effects.'),
       (161, 'Cherry AK-47', 'Sativa-dominant hybrid with euphoric and relaxed effects.'),
       (162, 'Lemon Kush', 'Hybrid with uplifting, euphoric, and relaxed effects.'),
       (163, 'Blue Hawaiian', 'Sativa-dominant hybrid with uplifting and euphoric effects.'),
       (164, 'LA Confidential', 'Indica with sedating, relaxing, and euphoric effects.'),
       (165, 'Godfather OG', 'Indica-dominant hybrid with sedating and relaxing effects.'),
       (166, 'Grape Kush', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (167, 'Strawberry Banana', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (168, 'Mango Kush', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (169, 'Gelato #41', 'Hybrid with euphoric, relaxing, and uplifting effects.'),
       (170, 'Black Diamond', 'Indica with relaxing, sleepy, and euphoric effects.'),
       (171, 'Lemon OG', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (172, 'Chemdawg 4', 'Hybrid with cerebral, uplifting, and euphoric effects.'),
       (173, 'ACDC', 'High-CBD hybrid with relaxed, happy, and focused effects.'),
       (174, 'Blue Diesel', 'Indica-dominant hybrid with relaxed and euphoric effects.'),
       (175, 'Orange Crush', 'Sativa with uplifting, euphoric, and energetic effects.'),
       (176, 'Master Kush', 'Indica with relaxed, sleepy, and euphoric effects.'),
       (177, 'Cannalope Haze', 'Sativa-dominant hybrid with uplifting and creative effects.'),
       (178, 'Hindu Kush', 'Indica with relaxing, euphoric, and sleepy effects.'),
       (179, 'Kosher Kush', 'Indica with relaxing, sedating, and euphoric effects.'),
       (180, 'Orange Cookies', 'Hybrid with euphoric, relaxing, and creative effects.'),
       (181, 'Golden Pineapple', 'Hybrid with uplifting, euphoric, and happy effects.'),
       (182, 'White Rhino', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (183, 'White Fire OG', 'Hybrid with euphoric, relaxed, and creative effects.'),
       (184, 'Blueberry Pie', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (185, 'Sour Grape', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (186, 'Kosher Tangie', 'Sativa-dominant hybrid with uplifting and creative effects.'),
       (187, 'Cotton Candy Kush', 'Indica-dominant hybrid with euphoric and relaxing effects.'),
       (188, 'Blue Cookies', 'Hybrid with relaxing, euphoric, and creative effects.'),
       (189, 'Blueberry Widow', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (190, 'Blue Mystic', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (191, 'Snowcap', 'Sativa-dominant hybrid with uplifting and creative effects.'),
       (192, 'Sour Tangie', 'Sativa-dominant hybrid with uplifting and euphoric effects.'),
       (193, 'Blueberry Dream', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (194, 'Blueberry AK', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (195, 'Sour Banana Sherbet', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (196, 'Blue Hawaiian OG', 'Sativa-dominant hybrid with uplifting and euphoric effects.'),
       (197, 'Purple Punch', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (198, 'Banana Kush', 'Indica-dominant hybrid with relaxing and euphoric effects.'),
       (199, 'Purple Tangie', 'Hybrid with happy, euphoric, and relaxed effects.'),
       (200, 'Blueberry Haze', 'Sativa-dominant hybrid with blueberry flavor and uplifting effects.');

ALTER SEQUENCE drug_drug_id_seq START WITH 201;

INSERT INTO supplier
VALUES (1, 'Pablo Escobar'),
       (2, 'El Chapo Guzman'),
       (3, 'Griselda Blanco'),
       (4, 'Frank Lucas'),
       (5, 'Freeway Ricky Ross'),
       (6, 'George Jung'),
       (7, 'Carlos Lehder'),
       (8, 'Dawood Ibrahim'),
       (9, 'Joaquín "El Chapo" Guzmán'),
       (10, 'Al Capone'),
       (11, 'Amado Carrillo Fuentes'),
       (12, 'Khun Sa'),
       (13, 'Alfredo Beltrán Leyva'),
       (14, 'Osiel Cárdenas Guillén'),
       (15, 'Dennis Allen'),
       (16, 'Christopher Coke'),
       (17, 'Howard Marks'),
       (18, 'Paul Lir Alexander'),
       (19, 'Drew Thornton'),
       (20, 'Carlos Enrique Lehder Rivas'),
       (21, 'Augusto José Ramón Pinochet Ugarte'),
       (22, 'Rajendra Nikalje'),
       (23, 'Gilberto Rodríguez Orejuela'),
       (24, 'Miguel Ángel Félix Gallardo'),
       (25, 'Salvatore Riina'),
       (26, 'Félix Gallardo'),
       (27, 'Anthony Salerno'),
       (28, 'Leroy Barnes'),
       (29, 'Richard Kuklinski'),
       (30, 'Ross Ulbricht'),
       (31, 'Luis Hernando Gómez Bustamante'),
       (33, 'Matteo Messina Denaro'),
       (34, 'Semion Mogilevich'),
       (35, 'Ibrahim Akasha'),
       (36, 'Jose Gonzalo Rodriguez Gacha'),
       (37, 'Giovanni Falcone'),
       (38, 'João Arcanjo Ribeiro'),
       (39, 'Larysa Holnyk'),
       (40, 'Juan Carlos Ramírez Abadía'),
       (41, 'Alfredo James Pacino'),
       (42, 'Roberto Suárez Goméz'),
       (44, 'Héctor Luis Palma Salazar'),
       (46, 'Ernesto Fonseca Carrillo'),
       (47, 'Sergei Mikhailov'),
       (48, 'Francisco Javier Arellano Félix'),
       (49, 'Juan José Esparragoza Moreno'),
       (50, 'James J. Bulger'),
       (51, 'Ismael Zambada García'),
       (52, 'Chepe Santacruz Londoño'),
       (54, 'Carlos Lehder Rivas'),
       (55, 'Gilberto José Rodríguez Orejuela'),
       (56, 'Nemesio Oseguera Cervantes'),
       (57, 'Ivan Urdinola Grajales'),
       (58, 'Francisco Rafael Arellano Félix'),
       (59, 'Humberto Álvarez Machaín'),
       (61, 'Eduardo Arellano Félix'),
       (62, 'Fabio Ochoa Vásquez'),
       (65, 'Abdul Latif Amado'),
       (66, 'James Michael Amsel'),
       (67, 'Joaquín Guzmán Loera'),
       (68, 'Jung In-bae'),
       (69, 'Alcides Ramón Wing López'),
       (71, 'Gustavo Álvarez Gardeazábal'),
       (72, 'Andreas Angelopoulos'),
       (73, 'James Joseph Bulger Jr.'),
       (74, 'Jorge Alberto Rodríguez'),
       (76, 'Abraham Abdallah'),
       (78, 'Jorge Luis Ochoa Vásquez'),
       (79, 'José Gonzalo Rodríguez Gacha'),
       (81, 'Víctor Manuel Mejía Múnera'),
       (83, 'José Evaristo Linares-Castillo'),
       (84, 'Rosalía Palma López'),
       (86, 'Jung Myung Seok'),
       (87, 'Alexi Suvorov'),
       (88, 'Carlos Castaño Gil'),
       (91, 'John Gotti');
ALTER SEQUENCE supplier_supplier_id_seq START WITH 92;

-- INSERTS 14 516 rows
DO
$$
    DECLARE
        rec CURSOR FOR (SELECT drug.drug_id, supplier.supplier_id
                        FROM drug
                                 CROSS JOIN supplier
                        EXCEPT
                        SELECT drug_id, supplier_id
                        FROM supplier_drug);
        pric        INTEGER;
        cleanlinnes VARCHAR(256);
        cons        VARCHAR(256);
        rate        NUMERIC(10, 2);
        avai        VARCHAR(256);
    BEGIN
        FOR hold IN rec
            LOOP
                pric := CAST(RANDOM() * 5000 AS INTEGER);
                CASE
                    WHEN RANDOM() < 0.33 THEN cleanlinnes := 'clean';
                    WHEN RANDOM() < 0.66 THEN cleanlinnes := 'medium';
                    ELSE cleanlinnes := 'dirty';
                    END CASE;
                CASE
                    WHEN RANDOM() < 0.25 THEN cons := 'dried';
                    WHEN RANDOM() < 0.50 THEN cons := 'liquid';
                    WHEN RANDOM() < 0.75 THEN cons := 'sniffgas';
                    ELSE cons := 'powder';
                    END CASE;
                rate := CAST(RANDOM() * 5 AS NUMERIC(10, 1));
                CASE
                    WHEN RANDOM() < 0.33 THEN avai := 'delivery';
                    WHEN RANDOM() < 0.66 THEN avai := 'on_street';
                    ELSE avai := 'warehouse';
                    END CASE;

                INSERT INTO supplier_drug
                VALUES (hold.supplier_id, hold.drug_id, pric, cleanlinnes, cons, rate, avai);
            END LOOP;
    END;
$$
LANGUAGE plpgsql;

COMMIT;